let humanScore = 0;
let computerScore = 0;
let currentRoundNumber = 1;

// Write your code below:
const generateTarget = () => {
    // Returns a random number that the user attempts to guess.
    return Math.floor(Math.random(1) * 10);
}

const compareGuesses = (user, computer, secret) => {
    // Returns the true if the human wins, false if not based on whether
    // user or computer is closest to the secret number generated by generateTarget.

    // First we get the absolute value of the user and computer guesses (distance from target)
    const absUser = Math.abs(secret - user);
    const absComputer = Math.abs(secret - computer);

    // If the user's absolute value is less than the computer, the user wins.
    if (absUser > absComputer) {
        return false;
    } else {
        return true;
    }
}

const updateScore = winner => {
    // Updates the score dependant on the winner of the round, incrementing score by 1 where
    // appropriate. 
    if (winner === 'human') {
        humanScore += 1;
    } else if (winner === 'computer') {
        computerScore += 1;
    }
}

// Advances the round for each go.
const advanceRound = () => currentRoundNumber++;